### ISSUE TITLE
Is there a way to check if this package is supported?

### ISSUE THREAD

**Issue by spaceemotion** [slevithan/regex#2]
I stumbled over this package as I was trying to improve the performance of our RegExes and noticed the disclaimer about the `v` flag that's required. I know that not every customer has a "modern" machine, so is there a way to check if this package is supported at all?

Something like `isSupported` to check if I can even use this setup would be nice, so that I can implement a fall back for older browsers/systems.

I guess one way of doing it is to check via a try-catch, but I am not sure if I am missing anything else:

```js
function isSupported() {
  try {
    new RegExp('', 'v');
    return true;
  } catch (e) {
    return false;
  }
}
```

**Comment by slevithan** [comment]
Your `isSupported` function should work great. You could also check for the existence of `RegExp.prototype.unicodeSets`.

Since `regex` supports using custom regex constructors (by modifying `this`), you can build yourself a fallback constructor that uses flag `u` instead of `v`. Flag `u` has had universal browser support since 2016 (see [compat table](https://caniuse.com/mdn-javascript_builtins_regexp_unicode)).

```js
import {regex} from 'regex';

const uregex = RegExp.prototype.hasOwnProperty('unicodeSets') ?
  regex :
  regex.bind(function(pattern, flags) {
    return new RegExp(pattern, flags.replace('v', 'u'));
  });

// Now you can use uregex instead of regex
uregex`…`;
```

This will throw if you try to interpolate more than one character node at a time *within a character class*, since in such cases `regex` generates syntax that is only valid with flag `v`. But otherwise, this should work fine.

**Comment by slevithan** [comment]
Added a link to this discussion in the readme, under *Compatibility*.

**Comment by slevithan** [comment]
As of v2.1.0, `regex` no longer relies on native support for flag <kbd>v</kbd> and works in much older browsers (see details in the readme under "Compatibility"). Testing for support should no longer be needed.
