### ISSUE TITLE
Feedback on the library

### ISSUE THREAD

**Issue by graphemecluster** [slevithan/regex#25]
Hello! Your DM suggested I share some thoughts on the library, but since it would be lengthy to fit into a single Twitter meessage, I put them into this issue. I think it might be too many to open one issue per item, so I've put them all here for you:

- It would be great if subroutines could be defined separately from the regex body.
  I could have defined them with variables outside and directly interpolated them without the use of subroutines, but consider:

  ```js
  const dateRegex = regex`\d{4}-\d{2}-\d{2}`; // I want to but can't name the variable `date`
  const { groups: { date, time } } = regex`(?<date>${dateRegex})[T ](?<time>${timeRegexFromElsewhere})`.exec(str);
  ```

  This causes pollution to the current scope, while

  ```js
  const { groups: { date, time } } = regex({
      subroutines: {
          date: regex`\d{4}-\d{2}-\d{2}`,
          time: timeRegexFromElsewhere,
      },
  })`(?<date>\g<date>)[T ](?<time>\g<time>)`.exec(str);
  ```

  doesn't.

- It might be out of scope, but you want to think about transforming Unicode properties that aren't yet supported in ECMAScript, i.e. those other than `General_Category`, `Script` and `Script_Extensions`. The particularly useful ones are `Block` (`blk`), `East_Asian_Width` (`ea`), `Numeric_Type` (`nt`) and `Vertical_Orientation` (`vo`). (I once needed `East_Asian_Width` in my project, and ended up another dependency specific to it.)

- Consider allowing direct interpolation after `\u`, `\p`, `\P` and `\q` to get rid of the tricky `{${…}}` syntax.

- A subtle one, but let's wrap [`regex.js` line 109](https://github.com/slevithan/regex/blob/53c8c863fbd848360fae7af632c9a845a11d55f6/src/regex.js#L109) in a `try` block such that the transformed `RegExp` is visible on error.

Some questions:

- What is the point to use `pattern`s instead of directly interpolating `regex`s inside a `regex`, given that flags can be altered and `RegExp`s can be nested with `regex` but not with `pattern`?

- Is there any particular reason not to use `[Symbol.match]` and `[Symbol.replace]` but a(n optional) wrapper class? Is it because using them would be insufficient to cover all cases?

**Comment by slevithan** [comment]
Thank you for the incredibly detailed, broad, and thoughtful review and feedback!! I'll respond with separate comments for each point.

> It would be great if subroutines could be defined separately from the regex body.
> I could have defined them with variables outside and directly interpolated them without the use of subroutines, but consider: [...] This causes pollution to the current scope, while [...] doesn't.

This is an interesting idea, and your design for how to do it seems really good. Presumably names provided via the `subroutines` option would take precedence over named groups in the regex that use the same name. However, I'm having trouble understanding the value that you would get in exchange for the complexity.

Why not do one of these?

```js
const {groups: {date, time}} = regex`(?<date> \d{4}-\d{2}-\d{2} ) [T ] (?<time> ${timeRegex} )`.exec(str);
const {groups: {date, time}} = regex`(?<date> ${regex`\d{4}-\d{2}-\d{2}`} ) [T ] (?<time> ${timeRegex} )`.exec(str);
```

Is the only benefit the readability improvement from defining the subpattern separately (without creating a variable)? If so, what about doing this:

```js
const {groups: {date, time}} = regex`
  (?<date> \d{4}-\d{2}-\d{2} )
  [T ]
  (?<time> ${timeRegex} )
`.exec(str);
```

Aside: You can even interpolate into a [subroutine definition group](https://github.com/slevithan/regex#subroutine-definition-groups).

**Comment by slevithan** [comment]
> It might be out of scope, but you want to think about transforming Unicode properties that aren't yet supported in ECMAScript, i.e. those other than `General_Category`, `Script` and `Script_Extensions`. The particularly useful ones are `Block` (`blk`), `East_Asian_Width` (`ea`), `Numeric_Type` (`nt`) and `Vertical_Orientation` (`vo`). (I once needed `East_Asian_Width` in my project, and ended up another dependency specific to it.)

It's not strictly out of scope, but I'm not sure it's appropriate to add these.

The philosophy behind `regex` is to remain lightweight (so it can be used in apps/libraries that run in browsers and care about bundle size) while augmenting native JS regex syntax with only the most broadly useful features that bring JS regex syntax to a modern standard, with a particular focus on improving regex readability.

ECMAScript excluded support for blocks specifically because they are ***not*** useful compared to other Unicode properties. Note that, before JS natively supported Unicode properties, I supported blocks in my older and heavier-weight [XRegExp](https://github.com/slevithan/xregexp) library, but in more recent versions XRegExp dropped support for blocks to better align with native JS.

I'm less familiar with `East_Asian_Width`, `Numeric_Type`, and `Vertical_Orientation`, but if they require adding a lot of Unicode character data to the bundle I'd be hesitant to bake them into `regex` even if they are commonly needed when dealing with East Asian scripts. The good news is they should be relatively easy to add via a `regex` plugin (see the collapsed details under [Readme: Options](https://github.com/slevithan/regex#-options)) with the help of [regex-utilities](https://github.com/slevithan/regex-utilities).

Probably something like this:

```js
import {regex} from 'regex';
import {replaceUnescaped} from 'regex-utilities';

function eastAsianWidth(expression) {
  const eaProperty = String.raw`\\(?<p>[pP])\{(?:ea|East_Asian_Width)=(?<value>[^\}]+)\}`;
  return replaceUnescaped(expression, eaProperty, (match, details) => {
    const {p, value} = match.groups;
    return `[${p === 'P' ? '^' : ''}${ /* ...TODO... */ }]`;
  });
}

const re = regex({plugins: [eastAsianWidth]})`...`;
```

**Comment by slevithan** [comment]
> Consider allowing direct interpolation after `\u`, `\p`, `\P` and `\q` to get rid of the tricky `{${…}}` syntax.

One of `regex`'s flagship features is 100% accurate ***context-aware*** interpolation, and this comes with some novel concepts when using interpolation into a `regex`. This is covered in some detail in the readme, and there are some important additional details in the collapsed "👉 **Show me some edge cases**" section within [Readme: Interpolating partial patterns](https://github.com/slevithan/regex#interpolating-partial-patterns).

In particular, values can safely be interpolated anywhere in a regex without worrying about their meaning being changed by (or making unintended changes in meaning to) the surrounding pattern. Since things like `\u` and `\u00` are errors on their own, an immediately-following interpolated value (intentionally) cannot change this to make it no longer an error. However, as noted in [Readme: Interpolation contexts](https://github.com/slevithan/regex#interpolation-contexts), there are special-case contexts for interpolating within enclosed tokens.

Without this handling, it would not be safe to interpolate an arbitrary string (that you want to be matched literally) at an arbitrary position within a regex. Right now, `regex`'s rules for atomization and sandboxing of interpolated values are relatively straightforward, and I think there is value in keeping it that way.

**Comment by slevithan** [comment]
> What is the point to use `pattern`s instead of directly interpolating `regex`s inside a `regex`, given that flags can be altered and `RegExp`s can be nested with `regex` but not with `pattern`?

First, the reason you can't interpolate a regex into a pattern is because patterns are not intended as an intermediate regex type. You can think of `pattern` as a directive to the `regex` tag: treat this string as a partial pattern rather than a string to be matched literally. In most cases, it is perfectly appropriate to not use `pattern` and instead interpolate a regex into `regex`. But there are some use cases where `pattern` is needed, which are listed under [Readme: Interpolating partial patterns](https://github.com/slevithan/regex#interpolating-partial-patterns):

- Composing a dynamic number of strings.
- Adding a pattern inside a character class (not allowed for `RegExp` instances since their top-level syntax context doesn't match).
- Dynamically adding backreferences without their corresponding captures (which wouldn't be valid as a standalone `RegExp`).
- When you don't want the pattern to specify its own, local flags.

Aside: I wrote some additional comments on why there is no type support or explicit handling for interpolating `pattern`s and `RegExp`s within `pattern`s [here](https://github.com/slevithan/regex/pull/20#issuecomment-2308771945).

**Comment by slevithan** [comment]
> A subtle one, but let's wrap [`regex.js` line 109](https://github.com/slevithan/regex/blob/53c8c863fbd848360fae7af632c9a845a11d55f6/src/regex.js#L109) in a `try` block such that the transformed `RegExp` is visible on error.

Great idea. 😊 I hadn't thought of this because Chromium-based browsers already show the transformed regex on error. But I just tested `` regex`\u` `` in Firefox and got only "Uncaught SyntaxError: invalid unicode escape in regular expression". So I agree this change would be helpful.

Which browser are you using?

**Comment by slevithan** [comment]
> Is there any particular reason not to use `[Symbol.match]` and `[Symbol.replace]` but a(n optional) wrapper class? Is it because using them would be insufficient to cover all cases?

Yes, it would be insufficient. *All* regex-using methods call `exec` (provided by the optional wrapper class, documented in the collapsed details for the `subclass` [option](https://github.com/slevithan/regex#-options)). Without overriding `exec` in the subclass, `regex` would need complex replacements for `split`, `replace`, etc. See also https://github.com/slevithan/regex/issues/15. I'm open to any ideas for improvements!

**Comment by slevithan** [comment]
> > A subtle one, but let's wrap [`regex.js` line 109](https://github.com/slevithan/regex/blob/53c8c863fbd848360fae7af632c9a845a11d55f6/src/regex.js#L109) in a `try` block such that the transformed `RegExp` is visible on error.
> 
> Great idea! [...]

I've now implemented this change and documented it in the [changelog](https://github.com/slevithan/regex/blob/main/CHANGELOG.md) for the next release. 😊

**Comment by slevithan** [comment]
Closing since all feedback has been addressed, but I'd be happy to continue the discussion and/or reopen.

**Comment by graphemecluster** [comment]
I'm sorry for the delay – I've just returned from my trip and am currently catching up on a number of tasks, so let me keep my response brief:

- That example about subroutines is artificial and would, of course, be more complicated in real-world use cases. My thought is to rely more on native JavaScript syntax and less on parsing with a manually written "parser". (My original assumption was that this would also enhance reusability and modularity, but I am now less convinced by these arguments in light of your reply.)

- We could potentially collaborate on an official, tree-shakable plugin package that covers every Unicode properties (I am unable to guaruentee that I will have the time to implement the majority of them by myself, but I would be happy to work on the ones you are less familiar with).

- Ah, I understand the rationale about forbidding direct interpolation now. I appreciate your decision and efforts to maintain simplicity in terms of both implementation and end-user ease of use.

- I'm unclear on what you are refering to by "Composing a dynamic number of strings." Could you give a brief explanation?

- > Which browser are you using?

  I ran a simple test with Bun, and yes, WebKit doesn't include the regex in the error message as in Safari. Thanks for the quick solution!

- Ah, I wasn't aware you had tried `[Symbol.*]` before.

**Comment by slevithan** [comment]
> I'm sorry for the delay

No problem at all! Now I'm sorry for *my* delay. 😊

> We could potentially collaborate on an official, tree-shakable plugin package that covers every Unicode properties (I am unable to guarantee that I will have the time to implement the majority of them by myself, but I would be happy to work on the ones you are less familiar with).

I'm very open to that, and welcome collaboration!! Unfortunately, at this time, I'd probably only be to able to contribute (apart from code review and discussion) if you set it up. But if you build a working system, I'd be very happy to contribute to it from there, and help ensure it's well integrated into the rest of the library, well tested and documented, etc. 😊 I'm excited about the potential.

> I'm unclear on what you are refering to by "Composing a dynamic number of strings." Could you give a brief explanation?

Sorry, I should have said "Composing a dynamic number of *escaped* strings." Here's an example (which assumes `arr` is an array of strings):

```js
// Instead of
new RegExp(`^(?:${
  arr.map(RegExp.escape).join('|')
})$`)

// You can say
regex`^${pattern(
  arr.map(a => regex`${a}`.source).join('|')
)}$`

// And you could add your own sugar that returns a `pattern` value
regex`^${anyOfEscaped(arr)}$`

// You could do the same thing without `pattern` by calling `regex` as a
// function instead of using it with backticks, then assembling the arguments
// list dynamically (but this is really ugly)
regex({raw: ['^(', ...Array(arr.length - 1).fill('|'), ')$']}, ...arr)
```

Note that an official `RegExp.escape` (which the example compares itself to) doesn't exist yet, and it's non-trivial to create your own version that comes close to the context-awareness of `regex`'s interpolation-based escaping, since there are tons of additional characters that might need to be escaped based on context (e.g., all `[A-Za-z]` if following `\c`, all `[0-9]` if following `\0` or a numbered backreference, all UnicodeSets reserved double punctuators (in character classes), etc., and you have to deal with incompatible escaping rules within character classes between flags `v` and `u`. None of the popular userland libraries for regex escaping even try to deal with these issues, so `regex` is by far the best way to escape regex special characters today. `pattern` makes its use as a regex escaping library even more robust by supporting the "dynamic number of escaped strings" use case.
