### ISSUE TITLE
Not supported in Safari 15.5

### ISSUE THREAD

**Issue by zhe-he** [slevithan/regex#27]
https://github.com/slevithan/regex/blob/ff7adf5a6f904b5c1c91a544efafb9c174e2baea/src/subroutines.js#L21C1-L28C1

I encountered a problem and found that Safari reported an error. Eventually, I pinpointed it to this location. In comparison to this, I wrote a simple regular expression. The image below shows the normal display and the error reported by Safari.

```js
var capturingDelim = String.raw`\((?!\?)(?!(?<=\(\?\()DEFINE\))`;
new RegExp(String.raw`
| (?<capturingStart>${capturingDelim})
`.replace(/\s+/g, ''), 'gsu');
```

<img width="399" alt="image" src="https://github.com/user-attachments/assets/3b8de2ee-602e-4e53-979c-c3bdeb061767">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/8ba2828c-db9d-4a48-a2af-9a7ff47192c2">

I directly imported `regex/dist/regex.min.js`, and I still get the same error when I open it with Safari.

**Comment by slevithan** [comment]
Thanks for the report. Yes, this is a known issue. Old Safari is not supported, since Regex+ relies on lookbehind which Safari was years late to support compared to other browsers (not until Safari 16.4, released, released 2023-03-27).

I'll leave this open for now, until I investigate if there are things I can do to work around this.

**Comment by slevithan** [comment]
Lookbehind is used in several places in the library, and it's problematic to remove all cases since that would introduce edge cases or significant complexity. So unfortunately, I don't plan to change this. I'll update the readme to note that Safari 16.4 is required.
