### ISSUE TITLE
Potential alternative for flags syntax

### ISSUE THREAD

**Issue by rauschma** [slevithan/regex#3]
(Very useful library, thanks for creating it!)

Another option for specifying RegExp flags is:

```
regex`/^.+/gm`
```

That is equivalent to:

```
regex('gm')`^.+`
```

Benefits:

* Fewer characters to type.
* Syntax should be more familiar to programmers.
* Easier to switch between RegExp literals and tagged templates.

One could make the slashes optional if there are no flags.

**Comment by slevithan** [comment]
Thanks, @rauschma! 😊

I agree with the advantages to that syntax which you outlined. But there are also some disadvantages:

- Doesn’t match the syntax within `RegExp`.
- Doesn’t match regex literal syntax either, since there are no multiline literals, and literals don’t allow unescaped `/` outside of character classes.
- Flags-up-front is more readable overall IMO, since some flags affect the meaning of regex syntax, and the presence of flags is easier to miss when they're at the end.
- If you allow taking the slashes off when not using flags, it creates avoidable syntax ambiguity (e.g. when you want to start a pattern with a literal `/`) in addition to convenience.
- Probable incompatibility with any future standardized regex tag. There has been some discussion in TC39 about a standardized regex tag (perhaps ``` RegExp.make`` ``` or ``` RegExp`` ```). Such discussions have not favored the `` `/.../flags` `` format.

I prefer to avoid ambiguity and conflict between flags by not supporting both the current method (flags as an argument) and trailing flags in the string.

But this would be easy to add via a user-side wrapper that only supports flags via the string. 😊

**Comment by rauschma** [comment]
* Makes sense!
* Independently of which approach is better, the library should indeed only support one syntax.

**Comment by rauschma** [comment]
(Aside: the content of your comment would make a great FAQ entry – it contains several interesting facts.)

**Comment by slevithan** [comment]
It took me a while, but per your suggestion, this is now covered by a new question in the [FAQ](https://github.com/slevithan/regex#-faq).
